Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
   config.vm.network "forwarded_port", guest: 8200, host: 8200, protocol: "tcp"

  config.vm.provider :virtualbox do |vb|
	vb.memory = 1024
	vb.cpus = 1
  end
end
