- hosts: sats
  remote_user: sushi
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python
    user_home: /media/user/persistence
  tasks:
    - name: Source .bashrc
      shell: source /home/sushi/.bashrc
      args:
        executable: /bin/bash
    
    - name: Create a keys folder
      file: 
        path: /home/sushi/.keys
        state: directory
    
    - name: Install npm dependencies
      npm:
        path: /home/sushi/api.sats.cc/typescript
    
    - name: Compile typescript
      command: /usr/bin/tsc
      args:
        chdir: /home/sushi/api.sats.cc/typescript

    - name: Copy final.bash WITH auth
      copy: 
        src: "{{ user_home }}/infra.sats.cc/final.bash"
        dest: /home/sushi/
        owner: sushi
        mode: u+rwx,g-rwx,o-rwx

    # - name: Run ditto to create response signing key pair
    #   shell: /usr/bin/node /home/sushi/api.sats.cc/typescript/dist/services/run/ditto.js crpf sats_sig
    #   args:
    #     executable: /bin/bash

    # - name: Run moltres server
    #   shell: /usr/bin/pm2 start moltres.js --watch
    #   args:
    #     chdir: /home/sushi/api.sats.cc/typescript/dist/services/run
    #     executable: /bin/bash
    

